/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, MODIFY YOUR OWN PROJECT
 * CODE TO FIT THE SPECIFICATION GIVEN BY THE TESTS IN THIS FILE.
 *
 * If you DO modify it, we overwrite it with a fresh version from our repo
 * when grading, so you can't use it to fudge the tests anyway.
 *
 * This file is used by the CS5801 auto-grading system.
 *
 * Please note, the assessment tests for grading, will use the same include
 * files, class names, and function names for accessing students' code that you
 * find in this file.  So students, if you write your code so that it passes
 * these feedback tests, you can be assured that the auto-grader will at least
 * be able to properly link with your code.
 */
/*******************************************************************************
* This test file are inspired by CS5801 Fall 2019
******************************************************************************/
 #ifdef CPL_READFILE_TESTS

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include <cmath>
#include <gtest/gtest.h>
#include "src/cpl.h"

class CPLReadFileTest : public ::testing::Test {

 protected:
  virtual void SetUp() {
    // Initialize anything for TESTS
  }

  CPL *cpl = new CPL();
};

/*******************************************************************************
 * Test Cases
 ******************************************************************************/

/*******************************************************************************
 * CPL ReadFile
 * - Input: a sample csv file
 * - Testing: value in the report after readfile.
 ******************************************************************************/
TEST_F(CPLReadFileTest, ReadFile) {
  cpl->ReadFile("cpl.csv");
  EXPECT_EQ(cpl->report_.GetNumTotalCandidates(), 17 ) << "FAIL: CPLReadFileTest:ReadFile - TotalCandidates is incorrect";
  EXPECT_EQ(cpl->report_.GetNumBallots(), 100 ) << "FAIL: CPLReadFileTest:ReadFile - NumBallots is incorrect";
  EXPECT_EQ(cpl->report_.GetNumTotalSeats(), 10 ) << "FAIL: CPLReadFileTest:ReadFile - TotalSeats is incorrect";
  /* There should be more for checking party and candidates.
  * However, at this point, report are incomplete
  * Still wait for the report to fully check other values.
  **/
};


#endif  // OPL_READFILE_TESTS
